version: "3.9"
services:
  mysql:
    image: mysql:latest
    container_name: db_notes
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - notas_mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile  # Route to backend Dockerfile
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile  # Route to frontend Dockerfile
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  notas_mysql_data:
